project_id = "xhnwedejrifeccvtiefs"

[functions.send-push-notification]
verify_jwt = false

[functions.send-scheduled-notifications]
verify_jwt = false

[functions.send-scheduled-test-notification]
verify_jwt = false

[functions.generate-intentions]
verify_jwt = false
